#!/bin/bash
#
# golang GOPATH switcher
#
_OLD_GOPATH_=$GOPATH
GOPATH=`pwd`
export GOPATH
export _OLD_PS1_=$PS1
export PS1="[\e[31;1mGO:$(basename $GOPATH)\e[0m] $PS1"
deactivate() {
    export PS1=$_OLD_PS1_
    export GOPATH=$_OLD_GOPATH_
    unset GOPATH
    unset _OLD_PS1_
    unset deactivate
}
